remote_theme: jekyll/minima

title: mugenmelon
author:
  name: mugenmelon
  email: mugenmelon@gmail.com
description: >-
  Software engineer developing an action RPG in his free time.
  Also makes tutorials & rants about programming or something.

minima:
  skin: auto
  social_links:
    - title: YouTube
      icon: youtube
      url: https://youtube.com/@mugenmelon
    - title: Twitch
      icon: twitch
      url: https://twitch.tv/mugenmelon
    - title: GitHub
      icon: github
      url: https://github.com/mugenmelon
    - title: X
      icon: x-twitter
      url: https://x.com/mugenmelon
    - title: Epic Dev Community
      icon: dev
      url: https://dev.epicgames.com/community/profile/pM6Ek/mugenmelon
