remote_theme: jekyll/minima@43f3ed0

title: mugenmelon
author:
  name: mugenmelon
  email: mugenmelon@gmail.com
description: Nil volentibus arduum. Divide et impera.

permalink: none

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      meta_tags: true
      published: false

minima:
  skin: dark
  show_excerpts: true
  social_links:
    - title: YouTube
      icon: youtube
      url: https://youtube.com/@mugenmelon
    - title: GitHub
      icon: github
      url: https://github.com/mugenmelon
    - title: Epic Dev Community
      icon: dev
      url: https://dev.epicgames.com/community/profile/pM6Ek/mugenmelon
    - title: X
      icon: x-twitter
      url: https://x.com/mugenmelon
